<a href="https://colab.research.google.com/github/datuvwxyz/Artificial-Intelligence/blob/main/Buoi_1_TTNT_(18_03_2024).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TRÍ TUỆ NHÂN TẠO BUỔI 1 (18/03/2024)**

In [ ]:
lst = [1, 3, "abc", ["GN", 1]]

print(lst[1])
print(len(lst))

lst[1] = "Tri tue nhan tao"

#print(lst[1])

4
Tri tue nhan tao


In [ ]:
tpl = (1, 3, "abc", [4, 1, 6], ("GN", 70, 80))

print(tpl[1])

#Loi do tuple khong the thay doi gia tri
tpl[1] = "Nuoc mat ca sau"

TypeError: 'tuple' object does not support item assignment

In [ ]:
set = {"Nhut", "Phu", "Trung", 2003}
print(set)

for x in set:
  print(x)

{2003, 2004, 'Nhut', 'Phu', 'Trung'}
2003
2004
Nhut
Phu
Trung


In [ ]:
dic = {
    "mssv" : "110121206",
    "lop" : "DA21TTC",
    "quequan" : ["Cau Ke", "Tra Vinh"]
}

print(dic)
print(dic["lop"])
print(dic["quequan"][0])

{'mssv': '110121206', 'lop': 'DA21TTC', 'quequan': ['Cau Ke', 'Tra Vinh']}
DA21TTC
Cau Ke


In [ ]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4,5,6]])
d = np.array([[[1,2,3], [4,5,6]], [[1,2,3], [4,5,6]]])

print(a)
print(b)
print(c)
print(d)

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

print(np.shape(a))
print(np.shape(b))
print(np.shape(c))
print(np.shape(d))

42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
0
1
2
3
()
(5,)
(2, 3)
(2, 2, 3)


In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[0])

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print("Phần tử thứ 2 dòng 1: ", arr[0, 1])

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])

print("Phần tử thứ 3 mảng thứ 2 của mảng đầu tiên: ", arr[0,1,2])

1
Phần tử thứ 2 dòng 1:  2
Phần tử thứ 3 mảng thứ 2 của mảng đầu tiên:  6


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

print(arr[4:])

print(arr[:4])

print(arr[-3:-1])

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[7 8 9]


In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([[1, 2, 3, 4],[5, 6, 7, 8]])
arr3 = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])

print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

(5,)
(2, 4)
(2, 2, 3)


In [ ]:
arr = np.array([1 , 2, 3, 4, 5, 6])

newarr = arr.reshape(3, 2)

print(newarr)

arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])

newarr1 = arr1.reshape(2, 4, 2)

print(newarr1)

[[1 2]
 [3 4]
 [5 6]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [ ]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

for x in arr:
  for y in x:
    print(y)

[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [ ]:
arr = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

for x in arr:
  for y in x:
    for z in y:
      print(z)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
1
2
3
4
5
6
7
8
9
10
11
12


##### CỘNG HAI MA TRẬN

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

add_arr = np.add(arr1, arr2)

print(add_arr)

[ 7  9 11 13 15]


##### TRỪ HAI MA TRẬN

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

sub_arr = np.subtract(arr1, arr2)

print(sub_arr)

[-5 -5 -5 -5 -5]


##### CHIA HAI MA TRẬN

In [ ]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

newarr = arr1.reshape(3,3)

print(newarr)

arr2 = newarr * 10

div_arr = np.divide(newarr, arr2)

print(div_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]


#NHÂN HAI MA TRẬN